import 'package:flutter/material.dart';

enum TipoConquista {
  primeiraVitoria,
  cinquentaPontos,
  cemPontos,
  cincoQuizesPerfeitos,
  todasMaterias,
  cinquentaEstrelas,
  dezQuizes,
  especialistaMat,
  especialistaPort,
  semErros,
  velocista,
  persistente,
  // Novas conquistas
  tresDiasConsecutivos,
  seteDiasConsecutivos,
  trintaDiasConsecutivos,
  noventaDiasConsecutivos,
  dezQuizesPerfeitos,
  vinteCincoQuizesPerfeitos,
  ultravelocista,
  velocistaAvancado,
  accuracy90_10,
  accuracy95_5,
  maratona3,
  cinquentaQuizesTotal,
  especialista20Mat,
  especialista20Port,
  pontos2000Mat,
  pontos2000Port,
  top10,
  top3,
  subir10posicoes,
  subir15posicoes,
  subir20posicoes,
  raro100_30,
  flash10,
  triplaPerfeicao,
  maratonaPerfeita,
  especialista50Mat,
  especialista50Port,
  mestrePrecisao,
  melhoriaContinua,
  exploradorTopicos,
  colecionador50,
  completionist,
  comeback30dias,
  desafiante,
  recuperar15posicoes,
}

class Conquista {
  final TipoConquista tipo;
  final String titulo;
  final String descricao;
  final IconData icone;
  final Color cor;
  final int pontos;
  final bool desbloqueada;
  final DateTime? dataDesbloqueio;

  Conquista({
    required this.tipo,
    required this.titulo,
    required this.descricao,
    required this.icone,
    required this.cor,
    required this.pontos,
    this.desbloqueada = false,
    this.dataDesbloqueio,
  });

  Conquista copyWith({
    bool? desbloqueada,
    DateTime? dataDesbloqueio,
  }) {
    return Conquista(
      tipo: tipo,
      titulo: titulo,
      descricao: descricao,
      icone: icone,
      cor: cor,
      pontos: pontos,
      desbloqueada: desbloqueada ?? this.desbloqueada,
      dataDesbloqueio: dataDesbloqueio ?? this.dataDesbloqueio,
    );
  }

  static List<Conquista> todasConquistas() {
    return [
      Conquista(
        tipo: TipoConquista.primeiraVitoria,
        titulo: '🎉 Primeira Vitória',
        descricao: 'Complete seu primeiro quiz',
        icone: Icons.flag,
        cor: Colors.green,
        pontos: 10,
      ),
      Conquista(
        tipo: TipoConquista.cinquentaPontos,
        titulo: '⭐ 50 Pontos',
        descricao: 'Alcance 50 pontos totais',
        icone: Icons.star,
        cor: Colors.amber,
        pontos: 20,
      ),
      Conquista(
        tipo: TipoConquista.cemPontos,
        titulo: '🏆 100 Pontos',
        descricao: 'Alcance 100 pontos totais',
        icone: Icons.emoji_events,
        cor: Colors.orange,
        pontos: 50,
      ),
      Conquista(
        tipo: TipoConquista.cincoQuizesPerfeitos,
        titulo: '💯 Perfeição',
        descricao: 'Complete 5 quizes com 100% de acertos',
        icone: Icons.verified,
        cor: Colors.purple,
        pontos: 100,
      ),
      Conquista(
        tipo: TipoConquista.todasMaterias,
        titulo: '📚 Multidisciplinar',
        descricao: 'Complete quiz em todas as matérias',
        icone: Icons.school,
        cor: Colors.blue,
        pontos: 50,
      ),
      Conquista(
        tipo: TipoConquista.cinquentaEstrelas,
        titulo: '🌟 Colecionador de Estrelas',
        descricao: 'Consiga 50 estrelas',
        icone: Icons.stars,
        cor: Colors.yellow,
        pontos: 75,
      ),
      Conquista(
        tipo: TipoConquista.dezQuizes,
        titulo: '🎯 Dedicado',
        descricao: 'Complete 10 quizes',
        icone: Icons.checklist,
        cor: Colors.teal,
        pontos: 30,
      ),
      Conquista(
        tipo: TipoConquista.especialistaMat,
        titulo: '🔢 Mestre da Matemática',
        descricao: 'Complete 10 quizes de Matemática',
        icone: Icons.calculate,
        cor: Colors.indigo,
        pontos: 40,
      ),
      Conquista(
        tipo: TipoConquista.especialistaPort,
        titulo: '📖 Mestre do Português',
        descricao: 'Complete 10 quizes de Português',
        icone: Icons.menu_book,
        cor: Colors.red,
        pontos: 40,
      ),
      Conquista(
        tipo: TipoConquista.semErros,
        titulo: '🎖️ Infalível',
        descricao: 'Complete um quiz sem errar nenhuma',
        icone: Icons.military_tech,
        cor: Colors.deepOrange,
        pontos: 50,
      ),
      Conquista(
        tipo: TipoConquista.velocista,
        titulo: '⚡ Velocista',
        descricao: 'Complete um quiz em menos de 2 minutos',
        icone: Icons.bolt,
        cor: Colors.yellow,
        pontos: 30,
      ),
      Conquista(
        tipo: TipoConquista.persistente,
        titulo: '💪 Persistente',
        descricao: 'Complete 5 quizes no mesmo dia',
        icone: Icons.fitness_center,
        cor: Colors.red,
        pontos: 60,
      ),
      // Novas conquistas
      Conquista(
        tipo: TipoConquista.tresDiasConsecutivos,
        titulo: '🔥 3 Dias Seguidos',
        descricao: 'Jogue por 3 dias consecutivos',
        icone: Icons.whatshot,
        cor: Colors.deepOrange,
        pontos: 25,
      ),
      Conquista(
        tipo: TipoConquista.seteDiasConsecutivos,
        titulo: '🔥 7 Dias Seguidos',
        descricao: 'Jogue por 7 dias consecutivos',
        icone: Icons.local_fire_department,
        cor: Colors.orange,
        pontos: 50,
      ),
      Conquista(
        tipo: TipoConquista.trintaDiasConsecutivos,
        titulo: '🔥 30 Dias Seguidos',
        descricao: 'Jogue por 30 dias consecutivos',
        icone: Icons.whatshot,
        cor: Colors.redAccent,
        pontos: 200,
      ),
      Conquista(
        tipo: TipoConquista.dezQuizesPerfeitos,
        titulo: '💯 10 Perfeitos',
        descricao: 'Complete 10 quizes com 100% de acertos',
        icone: Icons.verified_user,
        cor: Colors.purpleAccent,
        pontos: 150,
      ),
      Conquista(
        tipo: TipoConquista.vinteCincoQuizesPerfeitos,
        titulo: '💯 25 Perfeitos',
        descricao: 'Complete 25 quizes com 100% de acertos',
        icone: Icons.verified,
        cor: Colors.deepPurple,
        pontos: 400,
      ),
      Conquista(
        tipo: TipoConquista.ultravelocista,
        titulo: '⚡ Ultravelocista',
        descricao: 'Complete um quiz em menos de 60 segundos',
        icone: Icons.flash_on,
        cor: Colors.yellowAccent,
        pontos: 80,
      ),
      Conquista(
        tipo: TipoConquista.velocistaAvancado,
        titulo: '⚡ Velocista Avançado',
        descricao: 'Complete 5 quizes com menos de 2 minutos',
        icone: Icons.timer,
        cor: Colors.lightBlue,
        pontos: 90,
      ),
      Conquista(
        tipo: TipoConquista.accuracy90_10,
        titulo: '🎯 90%+ em 10 quizzes',
        descricao: 'Mantenha 90%+ de acerto em pelo menos 10 quizzes',
        icone: Icons.show_chart,
        cor: Colors.greenAccent,
        pontos: 120,
      ),
      Conquista(
        tipo: TipoConquista.accuracy95_5,
        titulo: '🎯 95%+ em 5 quizzes',
        descricao: 'Mantenha 95%+ de acerto em pelo menos 5 quizzes',
        icone: Icons.bar_chart,
        cor: Colors.lightGreen,
        pontos: 180,
      ),
      Conquista(
        tipo: TipoConquista.maratona3,
        titulo: '🏃 Maratona 3',
        descricao: 'Complete 3 quizzes seguidos no mesmo dia',
        icone: Icons.directions_run,
        cor: Colors.brown,
        pontos: 40,
      ),
      Conquista(
        tipo: TipoConquista.cinquentaQuizesTotal,
        titulo: '🏅 Maratonista',
        descricao: 'Complete 50 quizzes no total',
        icone: Icons.emoji_events,
        cor: Colors.indigoAccent,
        pontos: 300,
      ),
      Conquista(
        tipo: TipoConquista.especialista20Mat,
        titulo: '🔢 Especialista 20 Mat',
        descricao: 'Complete 20 quizzes de Matemática',
        icone: Icons.calculate,
        cor: Colors.indigo,
        pontos: 120,
      ),
      Conquista(
        tipo: TipoConquista.especialista20Port,
        titulo: '📖 Especialista 20 Port',
        descricao: 'Complete 20 quizzes de Português',
        icone: Icons.menu_book,
        cor: Colors.redAccent,
        pontos: 120,
      ),
      Conquista(
        tipo: TipoConquista.pontos2000Mat,
        titulo: '🔢 2000 Pontos Mat',
        descricao: 'Acumule 2000 pontos em Matemática',
        icone: Icons.calculate_outlined,
        cor: Colors.teal,
        pontos: 200,
      ),
      Conquista(
        tipo: TipoConquista.pontos2000Port,
        titulo: '📖 2000 Pontos Port',
        descricao: 'Acumule 2000 pontos em Português',
        icone: Icons.menu_book_outlined,
        cor: Colors.deepOrange,
        pontos: 200,
      ),
      Conquista(
        tipo: TipoConquista.especialista50Mat,
        titulo: '🔢 Especialista 50 Mat',
        descricao: 'Complete 50 quizzes de Matemática',
        icone: Icons.calculate_outlined,
        cor: Colors.indigo,
        pontos: 300,
      ),
      Conquista(
        tipo: TipoConquista.especialista50Port,
        titulo: '📖 Especialista 50 Port',
        descricao: 'Complete 50 quizzes de Português',
        icone: Icons.menu_book_rounded,
        cor: Colors.redAccent,
        pontos: 300,
      ),
      Conquista(
        tipo: TipoConquista.mestrePrecisao,
        titulo: '🏅 Mestre da Precisão',
        descricao: '95%+ de acerto em 50+ quizzes',
        icone: Icons.grade,
        cor: Colors.green,
        pontos: 350,
      ),
      Conquista(
        tipo: TipoConquista.melhoriaContinua,
        titulo: '📈 Melhoria Contínua',
        descricao: 'Aumente em 20% a média de pontos por quiz vs mês anterior',
        icone: Icons.trending_up,
        cor: Colors.lightGreen,
        pontos: 180,
      ),
      Conquista(
        tipo: TipoConquista.flash10,
        titulo: '⚡ Flash 10s',
        descricao: 'Complete um quiz em menos de 10 segundos',
        icone: Icons.flash_on,
        cor: Colors.pink,
        pontos: 500,
      ),
      Conquista(
        tipo: TipoConquista.triplaPerfeicao,
        titulo: '💯 Tripla Perfeição',
        descricao: '3 quizzes perfeitos em sequência',
        icone: Icons.filter_3,
        cor: Colors.purpleAccent,
        pontos: 220,
      ),
      Conquista(
        tipo: TipoConquista.maratonaPerfeita,
        titulo: '🔥 Maratona Perfeita',
        descricao: '5 quizzes perfeitos no mesmo dia',
        icone: Icons.whatshot,
        cor: Colors.deepOrangeAccent,
        pontos: 400,
      ),
      Conquista(
        tipo: TipoConquista.top3,
        titulo: '🏆 Top 3',
        descricao: 'Chegue ao top 3 do ranking geral',
        icone: Icons.emoji_events,
        cor: Colors.amber,
        pontos: 400,
      ),
      Conquista(
        tipo: TipoConquista.subir15posicoes,
        titulo: '⬆️ Subiu 15 posições',
        descricao: 'Suba 15 posições no ranking desde sua última sessão',
        icone: Icons.arrow_upward,
        cor: Colors.lightGreen,
        pontos: 120,
      ),
      Conquista(
        tipo: TipoConquista.subir20posicoes,
        titulo: '⬆️ Subiu 20 posições',
        descricao: 'Suba 20 posições no ranking desde sua última sessão',
        icone: Icons.trending_up,
        cor: Colors.green,
        pontos: 200,
      ),
      Conquista(
        tipo: TipoConquista.exploradorTopicos,
        titulo: '🧭 Explorador de Tópicos',
        descricao: 'Complete ao menos 1 quiz em cada tópico disponível',
        icone: Icons.explore,
        cor: Colors.cyan,
        pontos: 140,
      ),
      Conquista(
        tipo: TipoConquista.colecionador50,
        titulo: '🔐 Colecionador 50%',
        descricao: 'Desbloqueie 50% das conquistas',
        icone: Icons.collections,
        cor: Colors.blueGrey,
        pontos: 250,
      ),
      Conquista(
        tipo: TipoConquista.completionist,
        titulo: '🏅 Completionist',
        descricao: 'Desbloqueie todas as conquistas',
        icone: Icons.workspace_premium,
        cor: Colors.deepPurpleAccent,
        pontos: 1000,
      ),
      Conquista(
        tipo: TipoConquista.comeback30dias,
        titulo: '🔄 Comeback',
        descricao: 'Volte após 30 dias inativo e complete 3 quizzes',
        icone: Icons.replay,
        cor: Colors.orangeAccent,
        pontos: 90,
      ),
      Conquista(
        tipo: TipoConquista.desafiante,
        titulo: '🤝 Desafiante',
        descricao: 'Vença um desafio direto contra outro usuário',
        icone: Icons.sports_mma,
        cor: Colors.deepOrange,
        pontos: 180,
      ),
      Conquista(
        tipo: TipoConquista.recuperar15posicoes,
        titulo: '💪 Resiliente',
        descricao: 'Recupere 15 posições no ranking depois de uma queda',
        icone: Icons.reviews,
        cor: Colors.greenAccent,
        pontos: 160,
      ),
      Conquista(
        tipo: TipoConquista.top10,
        titulo: '🏆 Top 10',
        descricao: 'Chegue ao top 10 do ranking geral',
        icone: Icons.emoji_events_outlined,
        cor: Colors.amberAccent,
        pontos: 250,
      ),
      Conquista(
        tipo: TipoConquista.subir10posicoes,
        titulo: '⬆️ Subiu 10 posições',
        descricao: 'Suba 10 posições no ranking desde sua última sessão',
        icone: Icons.trending_up,
        cor: Colors.greenAccent,
        pontos: 150,
      ),
      Conquista(
        tipo: TipoConquista.raro100_30,
        titulo: '⚡ Perfeição Relâmpago',
        descricao: '100% de acerto e tempo < 30s (conquista rara)',
        icone: Icons.flash_on,
        cor: Colors.pinkAccent,
        pontos: 500,
      ),
    ];
  }
}
