name: sqeducaplay
description: "Aprender é divertido com o SQEducaPlay! Jogo educativo para crianças."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  confetti: ^0.8.0
  flutter_tts: ^4.2.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  google_fonts: ^8.0.2
  image_picker: ^1.2.2
  image_cropper: ^12.2.1
  permission_handler: ^12.0.1
  bcrypt: ^1.1.3
  path_provider: ^2.1.5
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/images/mascote.png" # PNG transparente do mascote
  remove_alpha_ios: true
  adaptive_icon_background: "#F3F9FF"
  adaptive_icon_foreground: "assets/images/mascote.png"

flutter_native_splash:
  color: "#F3F9FF"
  image: "assets/images/logo_full.png" # Logo completa (mascote + texto)
  branding: "assets/images/mascote.png"
  android_12:
    image: "assets/images/logo_full.png"
    icon_background_color: "#F3F9FF"
  web: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/